### ISSUE TITLE
Info on hub.docker.com still outdated

### ISSUE THREAD

**Issue by Tekki** [Raku/docker#20]
My comment in #15 didn't get noticed, I open a new issue.
Your repo on Docker Hub is not an automated build, you have to update the README manually.
[Here](https://docs.docker.com/docker-hub/builds/) you find more infos about automated builds. Seems it isn't possible to convert an existing repo, there is an open issue on Docker: https://github.com/docker/hub-feedback/issues/794

I don't want to be the one who always complains, so I'll propose some changes to the README.

**Comment by zakame** [comment]
Sounds like one needs to create a PR updating https://github.com/docker-library/docs/tree/master/rakudo-star

This can be semi-automated via adding an `update.sh` in this repo and letting @docker-library-bot commit here, cf https://github.com/Perl/docker-perl/pull/24#issuecomment-439660780

**Comment by Tekki** [comment]
Now that 2019.03 is on Dockerhub, why is the README still not updated?

**Comment by tianon** [comment]
That'd be because nobody has made a PR to https://github.com/docker-library/docs/tree/master/rakudo-star :smile:

To be clear, giving @docker-library-bot commit bits here would not do anything with `README.md` -- the format in https://github.com/docker-library/docs/tree/master/rakudo-star is different (and templated so that all official images have a consistent image description format).

The approach we take with images maintained under https://github.com/docker-library is to make the `README.md` inside the repository just a stub that points to Docker Hub as the canonical source (see https://github.com/docker-library/golang#readme, for example), which helps us avoid duplicated documentation effort.

Some other images prefer to keep the documentation on Docker Hub explicitly slim and link elsewhere for documentation (either to a markdown file in GitHub or better yet to actual upstream documentation content so the documentation for the image lives within the proper upstream documentation directly).

**Comment by JJ** [comment]
Let's see if I can take care of this...  But I don't have the permissions
in Docker Hub, so it might be for nothing...

**Comment by Tekki** [comment]
I have permission, and it's not required. But I think that an official maintainer has to make this PR.

**Comment by tianon** [comment]
It doesn't require any permissions of any kind -- we just need someone to take a look at https://github.com/docker-library/docs/blob/master/rakudo-star/content.md and provide a PR to that repository updating it as desired (which we then typically ask one of the image maintainers to sign-off on whether they approve of the changes).

**Comment by JJ** [comment]
Even more outdated now...

**Comment by moritz** [comment]
https://github.com/docker-library/docs/pull/1704

**Comment by moritz** [comment]
I've updated the info that I could find how to update. If stuff's still wrong, please open a merge request against docker-library/docs.
